// Auto-generated by Tour Editor
const START_SCENE = "ar/1BM.jpg";
const SCENES = {
  "ar/1BM.jpg": {
    "pano": "ar/1BM.jpg",
    "arrows": [
      {
        "pitch": -8.063907000923546,
        "yaw": -42.01466513973864,
        "next": "ar/1B-1.jpg"
      },
      {
        "pitch": -7.656826095670738,
        "yaw": -144.41341339710883,
        "next": "ar/1A-1.jpg"
      },
      {
        "pitch": -6.770067112383427,
        "yaw": 139.6950006332718,
        "next": "ar/1A1.jpg"
      }
    ]
  },
  "ar/1B-1.jpg": {
    "pano": "ar/1B-1.jpg",
    "arrows": [
      {
        "pitch": -13.881908716309189,
        "yaw": -94.33951241999054,
        "next": "ar/1BM.jpg"
      },
      {
        "pitch": -4.068339633809019,
        "yaw": 179.79185536993168,
        "next": "ar/1BC-1.jpg"
      },
      {
        "pitch": -9.773181475679724,
        "yaw": -0.9040752882225145,
        "next": "ar/1A-1.jpg"
      }
    ]
  },
  "ar/1BC-1.jpg": {
    "pano": "ar/1BC-1.jpg",
    "arrows": [
      {
        "pitch": -10.476343118911164,
        "yaw": 90.56627853823991,
        "next": "ar/1B-1.jpg"
      }
    ]
  },
  "ar/1A-1.jpg": {
    "pano": "ar/1A-1.jpg",
    "arrows": [
      {
        "pitch": -12.213555790489227,
        "yaw": -2.274885551309415,
        "next": "ar/1B-1.jpg"
      },
      {
        "pitch": -14.034398748184543,
        "yaw": 90.35070748496987,
        "next": "ar/1BM.jpg"
      },
      {
        "pitch": -1.3950191773791152,
        "yaw": -90.8365985049037,
        "next": "ar/1A-3.jpg"
      }
    ]
  },
  "ar/1A1.jpg": {
    "pano": "ar/1A1.jpg",
    "arrows": [
      {
        "pitch": -17.465453674056327,
        "yaw": -178.40351103931377,
        "next": "ar/1BM.jpg"
      },
      {
        "pitch": -0.10664774362585053,
        "yaw": 1.6354893807871855,
        "next": "ar/1A2.jpg"
      }
    ]
  },
  "ar/1A2.jpg": {
    "pano": "ar/1A2.jpg",
    "arrows": [
      {
        "pitch": -3.7250064888280345,
        "yaw": -2.629871038624652,
        "next": "ar/1A1.jpg"
      }
    ]
  },
  "ar/1A-3.jpg": {
    "pano": "ar/1A-3.jpg",
    "arrows": [
      {
        "pitch": -2.5988624614833795,
        "yaw": 94.38126378403122,
        "next": "ar/1A-1.jpg"
      },
      {
        "pitch": -2.736320118963829,
        "yaw": -0.14225481410219143,
        "next": "ar/1BC1.jpg"
      }
    ]
  },
  "ar/1BC1.jpg": {
    "pano": "ar/1BC1.jpg",
    "arrows": [
      {
        "pitch": -4.319695839727961,
        "yaw": -2.345157930388642,
        "next": "ar/1A-3.jpg"
      }
    ]
  }
};